//
// Copyright (c) 2020-2021, 2023 NVI, Inc.
//
// This file is part of the VLBI gromet_install distribution.
// (see http://github.com/nvi-inc/gromet_install).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

:doctype: book

= DRAFT gromet installation for FS computers
E. Himwich, K.Imai, C. Frock, C. Coughlin
Version 1.2 - September 2023

:sectnums:
:experimental:
:downarrow: &downarrow;
:uparrow: &uparrow;

:toc:

== Revision history

* 1.1 -- August 2023 -- Correct MET4 bar command to `3`

* 1.0 -- August 2021 -- Initial version

== Introduction

This document provides instructions for installing _gromet_ (a met.
data server) for Field System computers. It is assumed that there are
both _operational_ and _spare_ computers in use. They are referred to
as _fs1_ and _fs2_, respectively. You should of course replace those
with the names of the computers you are using, if different. If there
is only one computer, you can omit the actions involving _fs2_. If you
do install on _fs2_, _gromet_ should be disabled there until it is
needed.

The repository for _gromet_ can be found at
https://github.com/nvi-inc/gromet.

The installation process uses the _recoverable testing_ procedure of
FSL10 with a RAID to enable easy recovery in case of a problem. This
has the advantage that if (i) actions are missing from the _gromet_
installation procedure or (ii) errors occur, and either or both can't
be recovered from directly, it is relatively easy to return to the
original state and start over. If you are using some other FSL__x__ or
don't have a RAID, you should skip using the recoverable testing
procedure and recovery or substitute a different one.

== Reverting the installation

If it is not possible finish the installation before the next
operational use of the system or disk rotation, the systems can be
reverted to their previous configuration. For each system that had the
primary disk _dropped_ follow the _failed_ branch of the recoverable
testing procedure at
https://nvi-inc.github.io/fsl10/raid.html#_recoverable_testing.

It will require several hours for the refresh operation to complete.
The system can be used for operations, but not a disk rotation, while
the refresh is in progress. Later, the installation can be tried again
from scratch when it is convenient.

Depending on where in the process the decision to revert the
installation is made, it may also be necessary to move the MET4A and
wind sensor serial connectors back to _fs1_.

== Setup the hardware

=== Perle IOLAN SDS2 G Device Server

. Set DIP switch to _serial_. It may need to be _console_ for the first setup.

. Configure to have the correct IP address and netmask.
+
The Perle _Device Manager_ software can be used for this.

. Connect to the correct Ethernet switch.

. Configure to have the correct setup for each serial device:
+
Connect to the device with a Web Browser.
+
NOTE: You could use the Perle _Device Manager_ instead.

.. For Serial #1:

  General: TCP sockets, Port: 10001, multiple connections
  Advanced: TCP keep alive
  Hardware: EIA-232/485, 9600, 8, N, 1
    for 232: full duplex
    for 485: half/full duplex as needed; for half, enable echo suppression
  Packet forwarding: Minimize Latency

.. For serial #2, use same setuo except use port `10002`.

.. Optionally set serial #1 device to met4a and #2 to wind

More information about this device can be found at
https://www.perle.com/products/iolan-sdg-device-server.shtml.

=== Paroscientific MET4A met. sensor

. If necessary, use a serial connection and a terminal emulator such
as _putty_, _screen_, or the Paroscientific utility _DQI3_, to
configure the line protocol.

+

The serial line configuration is 9600 BAUD, no parity, 8 data bits,
and 1 stop bit, Use RS232 or RS485 as needed.

. Connect MET4A to Perle serial port #1

. Configure device, e.g. on Linux use `nc _ip_ 10001` to connect to
the device at IP address `_ip_`.

+

NOTE: You could use a serial connection and a terminal emulator instead.

.. Set device to respond in _bars_ for pressure with:

 *0100EW*0100UN=3

.. Test for response with:

  *0100P9

+

Example output:

  $WIXDR,P,.885475,B,DQ146664,C,15.61,C,DQ20356187,H,100.00,P,DQ20356187

More information about this device can be found at
http://paroscientific.com/pdf/8008-001_Manual_for_MET4_and_MET4A_Meteorological_Measurement_Systems.pdf.

=== Vaisala WMT70x wind sensor

. If necessary, use a serial connection and a terminal emulator such as _putty_, _screen_, or the Paroscientific utility _DQI3_, to configure the line protocol.
+
The serial line configuration is 9600 BAUD, no parity, 8 data bits, and 1 stop bit, Use RS232 or RS485 as needed.

. Connect WMT70__x__ to Perle serial port #2

. Configure device, e.g. on Linux use `nc _ip_ 10002` to connect to the device at IP address `_ip_`.
+
NOTE: You could use a serial connection and a terminal emulator instead.

.. Open command mode (can be entered as output is coming out):

 $0OPEN

.. Stop output with:

  STOP

.. Configure for WS425 A/B Standard Data Message auto-send:

 S autoSend,19

.. Speed in meters/second:

 S wndUnit,0

.. Output once per second:

 S autoInt,1

.. Start output:

 START
+
Output should start coming out once per second, e.g.:

 $WIMWV,284,R,004.3,M,A*37

More information about this device can be found at
https://docs.vaisala.com/r/M211095EN-K/en-US.

== fs1 installation

All work in this section is to be performed on the _fs1_ computer.

=== Preparing fs1

. Follow the directions for the recoverable test procedure at
https://nvi-inc.github.io/fsl10/raid.html#_recoverable_testing.

. Once the primary disk has been dropped from the RAID, move onto the
next step, <<Installing gromet on fs1>>, below.

=== Installing gromet on fs1

. Remove any previous installation of `gromet`.

. As _root_, install or update the _go_ language installation

.. Run _fsadapt_:

    cd ~/fsl10
    ./fsadapt

+

In `fsadapt`:

+

NOTE: Use kbd:[Space] to toggle actions, `*` is selected, empty
(space) is not selected. Use kbd:[{uparrow}] and kbd:[{downarrow}] to
navigate between actions. Use kbd:[Tab] to change whether `<OK>` or
`<Cancel>` is selected (inverse video) at the bottom.

+

.. On the first screen, make sure _only_ the `goinst` option is
selected, then with `OK` highlighted, press kbd:[Enter].

.. On the second screen, use kbd:[Tab] to select `Cancel` then press
kbd:[Enter].

. As _prog_:

.. Set the `PATH` for _go_ in _~/.profile_

+

Make sure the lines:

    export GOPATH=~/go
    PATH="$GOPATH/bin:/usr/local/go/bin:$PATH"
+
are uncommented.

.. Reload the `PATH`:
+
....
. ~/.profile
....

.. Download and `make` gromet

    cd /usr2/st
    git clone https://github.com/nvi-inc/gromet.git
    cd gromet
    make

.. Create the local configuration directory:

+
    cd /usr2/st
    mkdir gromet.conf

.. Place the _README_ file in the directory. A pointer to an example
file and a listing of it are provided in the appendix
<<README file>>.

.. Copy the default _gromet.service_, and _gromet.yml_ files into the
directory.

    cd /usr2/st/gromet
    cp gromet.service gromet.yml ../gromet.conf

. As _oper_ setup _/usr2/control/gromet.yml_:

.. Copy file to _/usr2/control_:

  cd /usr2/control
  cp /usr2/st/gromet.conf/gromet.yml .

.. Change the `listen_address` as needed. Typically, `127.0.0.1:50001`
would be used to serve met. data to the local host. All clients on the
local host should use the same address to connect to _gromet_. To
server data to the network, use the host alias for this machine from
_/etc/hosts_ in place of `127.0.0.1`. In this case, all clients, on
the local host or other hosts, should use an alias that resolves to
this host's IP address.

+

NOTE: You may need to adjust any local host and internal site
firewalls to allow devices to access _gromet_ if it is serving to the
network.

.. Change the hostname/IP (in the `address` lines before the `:10001`
and `:10002`) for the devices to whatever is required. Usually an
alias (perhaps `met`) in _/etc/hosts_ would be used.

+

+

NOTE: You may need to adjust the internal site firewalls to allow
_gromet_ to access to the Perle server (`met`).

.. Change the port numbers to be correct for the Perle converter if
they are not `10001` for the MET4A and `10002` for the wind sensor.

.. If you have a MET3 or MET4 sensor, instead of a MET4A, adjust the
`type` line accordingly.

. As _prog_:

+

Copy the updated _gromet.yml_ back to the `/usr2/st/gromet.conf`
directory:

    cp /usr2/control/gromet.yml /usr2/st/gromet.conf

+

If it is safe, answer `*y*` if prompted to confirm.

. As _root_:

.. Add the alias (perhaps `met`) for the Perle Etherent converter to _/etc/hosts_ if not already present.

.. If _metserver_ and _metclient_ were previously install, stop their services:

   systemctl stop metclient
   systemctl stop metserver

.. Move the MET4A and wind sensor serial connections to the serial
connectors on the Perle Ethernet converter.

.. Install _gromet_ as a service on this machine.

    cd /usr2/st/gromet
    make install

+

Answer `*n*` to not overwrite _gromet.yml_ if you have already configured it as above.

+

.. Start the _gromet_ service:

    systemctl start gromet

== Testing gromet on fs1

. Use the `wx` command in the FS to verify met. data is still available.

. Check in _grafana_ on the MAS to verify that the met. data are updating.

== fs2 installation

Once _fs1_ has been successfully set-up, the _fs2_ disks, running in
the spare computer, can be set-up. Do not proceed with this section
until _gromet_ is working on _fs1_.

=== Preparing fs2

Follow the instructions in the <<Preparing fs1>> step above, but this
time doing them on _fs2_. Then proceed with the next step below
<<Changes needed before installing gromet on fs2>>.

=== Changes needed before installing gromet on fs2

For this part of the installation it will be necessary to take some
additional actions:

. Terminate the FS on _fs1_.

. Stop _gromet_ on _fs1_, as _root_:

    systemctl stop gromet

=== Installing gromet on fs2

Follow the directions in the <<Installing gromet on fs1>> step
above, but this time performing the actions on _fs2_. Then proceed to
the next section below, <<Testing gromet on fs2>>.

== Testing gromet on fs2

Use the `wx` command in the FS to verify met. data is still available.

== Finishing up

This section covers the actions to follow once _gromet_ has been
tested successfully on _both_ _fs1_ and _fs2_.

=== Finalizing fs2

. Terminate the FS on _fs2_.

. Disable and stop _gromet_ on _fs2_, as _root_:

    systemctl disable gromet
    systemctl stop gromet

=== Finalizing fs1

. Start _gromet_ (and if in use, _metclient_), and if it was in use, disable _metserver_
on _fs1_, as _root_:

    systemctl start gromet
    systemctl start metclient
    systemctl disable metserver

+

NOTE: Skip the _metserver_ command if it was not in use. Skip the
_metclient_ command if it is not being used.

. Reverify the results of the <<Testing gromet on fs1>> section above.

=== Remove go

Unless you want to keep _go_ installed, use the following command
as _root_ to remove _go_ on both _fs1_ and _fs2_:

    rm -rf /usr/local/go

. Remove _go_ on _fs1_.

. Remove _go_ on _fs2_.

== Restoring RAIDs

If everything is still working, follow the _successful_ branch in the
recoverable test procedure, to recover the RAIDs on both _fs1_ and
_fs2_ at
https://nvi-inc.github.io/fsl10/raid.html#_recoverable_testing to:

. Recover the RAID on _fs1_.

. Recover the RAID on _fs2_.

[appendix]

= README file

An example can be found in the file _README_ at
https://github.com/nvi-inc/gromet_install. A listing is provided
below.

....
Install

  root:
  install go with fsadapt

  prog:
    cd /usr2/st
    git clone https://github.com/nvi-inc/gromet.git
    cd gromet
    make

  root:
    cd /usr2/st/gromet
    make install

   oper:
   update /usr2/control/gromet.yml as needed,
     recent copy in /usr2/st/gromet.conf

  root:
    systemctl start gromet

on the spare machine:
     systemctl disable gromet
     systemctl stop gromet
until needed, then:
     systemctl enable gromet
     systemctl start gromet
(and disable/stop on other machine)
....
